// src/components/pages/Home.jsx
import {Link} from "react-router-dom";
import {useEffect, useState} from "react";
import fetchIndex from "../../data/index.jsx";

function GetHome() {
    const [home, setHome] = useState([]);

    useEffect(() => {
        fetchIndex().then((index) => {
            setHome(Object.keys(index).map((key) => (
                <div className="resource-card" key={key}>
                    <span className="resource-label">{key}: </span>
                    <Link className="resource-link" to={`/${key}`}>
                        {index[key]}
                    </Link>
                </div>
            )));
        });
    }, []);

    return <div className="resource-list">{home}</div>;
}

export default GetHome;

// src/components/pages/Home.vue
<script setup>
import { onMounted, ref } from "vue";
import fetchIndex from "../../data/index.js";

const home = ref({});

onMounted(async () => {
  home.value = await fetchIndex();
});
</script>

<template>
  <div class="resource-list">
    <div v-for="key in Object.keys(home)" :key="key" class="resource-card">
      <span class="resource-label">{{ key }}: </span>
      <RouterLink class="resource-link" :to="`/${key}`">
        {{ home[key] }}
      </RouterLink>
    </div>
  </div>
</template>
