// src/components/entities/Audioboek.jsx
import {useEffect, useState} from "react";
import {useParams, Link, useLocation} from "react-router-dom";
import {
    buildResourcePath,
    decodeResourceParam,
    findResourceBySlug,
    getAudiobookName,
    isEncodedApiUrl,
} from "../../utils/resourceRouting.js";
import ResourceReferenceLink from "./ResourceReferenceLink.jsx";

function GetAudiobookComponent() {
    const {slug} = useParams();
    const location = useLocation();
    const [audiobook, setAudiobook] = useState({});

    useEffect(() => {
        let ignore = false;

        async function load() {
            const stateUrl = location.state?.resourceUrl;
            if (stateUrl) {
                const resource = await fetchJSONfromAudiobook(stateUrl);
                if (!ignore) {
                    setAudiobook(resource);
                }
                return;
            }

            if (isEncodedApiUrl(slug)) {
                const link = decodeResourceParam(slug);
                const resource = await fetchJSONfromAudiobook(link);
                if (!ignore) {
                    setAudiobook(resource);
                }
                return;
            }

            const resource = await findResourceBySlug("audiobooks", slug, getAudiobookName);
            if (!ignore) {
                setAudiobook(resource);
            }
        }

        void load().catch(console.error);
        return () => {
            ignore = true;
        };
    }, [location.state, slug]);

    return (
        <div className="entity-table-wrapper">
            <table className="entity-table">
                <tbody>
                {Object.entries(audiobook).map(([key, value]) => (
                    <tr key={key}>
                        <th>{key}</th>
                        <td>{makeCellContent(key, value, audiobook)}</td>
                    </tr>
                ))}
                </tbody>
            </table>
        </div>
    );
}

async function fetchJSONfromAudiobook(link) {
    let result = await fetch(link).then(response => {
        if (response.ok) {
            return response;
        } else {
            throw new Error('API call for audiobook details failed with status ' + response.status);
        }
    });
    return await result.json();
}

function makeCellContent(key, value, audiobook) {
    if (key === "genres") {
        return value.map((genreUrl) => (
            <div key={`${key}-${genreUrl}`}>
                <ResourceReferenceLink
                    resourceType="genres"
                    resourceUrl={genreUrl}
                    fallbackLabel={String(genreUrl)}
                />
            </div>
        ));
    }

    if (["reviews", "positions"].includes(key)) {
        return value.map((v) => (
            <div key={`${key}-${v}`}>
                <Link to={`/${key}/${encodeURIComponent(v)}`}>
                    {String(v)}
                </Link>
            </div>
        ));
    }

    if (key === "url") {
        return (
            <Link to={buildResourcePath("audiobooks", audiobook, getAudiobookName)} state={{resourceUrl: value}}>
                {String(value)}
            </Link>
        );
    }

    if (key === "index") {
        return (
            <Link to="/audiobooks">
                {String(value)}
            </Link>
        );
    }

    if (key === "authors") {
        return value.map((v) => <div key={`${key}-${v}`}>{String(v)}</div>);
    }

    if (key === "link") {
        return (
            <Link to={`${value}`}>
                {String(value)}
            </Link>
        );
    }

    return String(value);
}

export default GetAudiobookComponent;

// src/components/entities/Audioboek.vue
<template>
  <div class="entity-table-wrapper">
    <table class="entity-table">
      <tbody>
        <tr v-for="[key, value] in Object.entries(audiobook)" :key="key">
          <th>{{ key }}</th>
          <td>
            <!-- genres -->
            <div v-if="key === 'genres'">
              <ResourceReferenceLink
                v-for="genreUrl in value"
                :key="'genres-' + genreUrl"
                resourceType="genres"
                :resourceUrl="genreUrl"
                :fallbackLabel="String(genreUrl)"
              />
            </div>
            <!-- reviews and positions -->
            <div v-else-if="['reviews', 'positions'].includes(key)">
              <router-link
                v-for="v in value"
                :key="key + '-' + v"
                :to="'/' + key + '/' + encodeURIComponent(v)"
              >
                {{ String(v) }}
              </router-link>
            </div>
            <!-- url -->
            <router-link
              v-else-if="key === 'url'"
              :to="{ path: buildResourcePath('audiobooks', audiobook, getAudiobookName), state: { resourceUrl: value } }"
            >
              {{ String(value) }}
            </router-link>
            <!-- index -->
            <router-link v-else-if="key === 'index'" to="/audiobooks">
              {{ String(value) }}
            </router-link>
            <!-- authors -->
            <div v-else-if="key === 'authors'">
              <div v-for="v in value" :key="'authors-' + v">{{ String(v) }}</div>
            </div>
            <!-- link -->
            <router-link v-else-if="key === 'link'" :to="value">
              {{ String(value) }}
            </router-link>
            <!-- default -->
            <span v-else>{{ String(value) }}</span>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import ResourceReferenceLink from './ResourceReferenceLink.vue'
import {
  buildResourcePath,
  decodeResourceParam,
  findResourceBySlug,
  getAudiobookName,
  isEncodedApiUrl,
} from '../../utils/resourceRouting.js'

const route = useRoute()
const router = useRouter()
const audiobook = ref({})

onMounted(async () => {
  const slug = route.params.slug
  const stateUrl = route.query.resourceUrl || router.currentRoute.value.state?.resourceUrl

  if (stateUrl) {
    audiobook.value = await fetchJSONfromAudiobook(stateUrl)
    return
  }

  if (isEncodedApiUrl(slug)) {
    const link = decodeResourceParam(slug)
    audiobook.value = await fetchJSONfromAudiobook(link)
    return
  }

  audiobook.value = await findResourceBySlug('audiobooks', slug, getAudiobookName)
})

async function fetchJSONfromAudiobook(link) {
  const response = await fetch(link)
  if (!response.ok) {
    throw new Error('API call for audiobook details failed with status ' + response.status)
  }
  return await response.json()
}
</script>
