// src/components/entities/Positie.vue
<template>
  <div class="entity-table-wrapper">
    <table class="entity-table">
      <tbody>
        <tr v-for="[key, value] in Object.entries(position)" :key="key">
          <th>{{ key }}</th>
          <td>
            <!-- user -->
            <ResourceReferenceLink
              v-if="key === 'user'"
              resourceType="users"
              :resourceUrl="value"
              :fallbackLabel="String(value)"
            />
            <!-- audiobook -->
            <ResourceReferenceLink
              v-else-if="key === 'audiobook'"
              resourceType="audiobooks"
              :resourceUrl="value"
              :fallbackLabel="String(value)"
            />
            <!-- url -->
            <router-link
              v-else-if="key === 'url'"
              :to="'/positions/' + encodeURIComponent(value)"
            >
              {{ String(value) }}
            </router-link>
            <!-- index -->
            <router-link v-else-if="key === 'index'" to="/positions">
              {{ String(value) }}
            </router-link>
            <!-- default -->
            <span v-else>{{ String(value) }}</span>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import ResourceReferenceLink from './ResourceReferenceLink.vue'

const route = useRoute()
const position = ref({})

onMounted(async () => {
  const url = route.params.url
  const link = decodeURIComponent(url)
  position.value = await fetchJSONfromPosition(link)
})

async function fetchJSONfromPosition(link) {
  const response = await fetch(link)
  if (!response.ok) {
    throw new Error('API call for position details failed with status ' + response.status)
  }
  return await response.json()
}
</script>

// src/components/entities/Positie.jsx
import {useEffect, useState} from "react";
import {useParams, Link} from "react-router-dom";
import ResourceReferenceLink from "./ResourceReferenceLink.jsx";

function GetPositionComponent() {
    const {url} = useParams();
    const [position, setPosition] = useState({});

    useEffect(() => {
        const link = decodeURIComponent(url);
        fetchJSONfromPosition(link).then(setPosition);
    }, [url]);

    return (
        <div className="entity-table-wrapper">
            <table className="entity-table">
                <tbody>
                {Object.entries(position).map(([key, value]) => (
                    <tr key={key}>
                        <th>{key}</th>
                        <td>{makeCellContent(key, value)}</td>
                    </tr>
                ))}
                </tbody>
            </table>
        </div>
    );
}

async function fetchJSONfromPosition(link) {
    let result = await fetch(link).then(response => {
        if (response.ok) {
            return response;
        } else {
            throw new Error('API call for position details failed with status ' + response.status);
        }
    });
    return await result.json();
}

function makeCellContent(key, value) {
    if (key === "user") {
        return (
            <ResourceReferenceLink
                resourceType="users"
                resourceUrl={value}
                fallbackLabel={String(value)}
            />
        );
    }

    if (key === "audiobook") {
        return (
            <ResourceReferenceLink
                resourceType="audiobooks"
                resourceUrl={value}
                fallbackLabel={String(value)}
            />
        );
    }

    if (key === "url") {
        return (
            <Link to={`/positions/${encodeURIComponent(value)}`}>
                {String(value)}
            </Link>
        );
    }

    if (key === "index") {
        return (
            <Link to="/positions">
                {String(value)}
            </Link>
        );
    }

    return String(value);
}

export default GetPositionComponent;
